#服务端口
server:
  port: 8088
#开启所有端点
management:
  endpoints:
    web:
      exposure:
        include: "*"
#配置Mybatis
#mybatis:
#  mapper-locations: classpath:mapping/*.xml
#  type-aliases-package: com.gainer.school.approval.dao
#  configuration:
#    map-underscore-to-camel-case: true
mybatis-plus:
  global-config:
    db-config:
      id-type: AUTO
      logic-delete-field: deleted
      logic-not-delete-value: 0
      logic-delete-value: 1
  # 打印sql
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
