server:
  port: 8090


mybatis:
  mapper-locations: classpath:mapping/*.xml
  type-aliases-package: com.lcw.common.pojo
  configuration:
    map-underscore-to-camel-case: true

spring:
  profiles:
    active:  dev
